version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    volumes:
      - ./:/usr/src/app
    ports:
      - 1433:1433
    working_dir: /usr/src/app 
    command: bash -c ' chmod +x ./mssql.entrypoint.sh; ./mssql.entrypoint.sh & /opt/mssql/bin/sqlservr;'

  pgsql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./pgsql.create-database.sql:/docker-entrypoint-initdb.d/pgsql.create-database.sql
    ports:
      - 5432:5432

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - ./mysql.create-database.sql:/docker-entrypoint-initdb.d/mysql.create-database.sql
    ports:
      - 3306:3306
